language: node_js

node_js:
  - "0.11"
  - "0.10"

env:
  global:
    - secure: Be5BoCC49zr7fGajHU/HlI79wwNaM+5RqAkheB7UVwguK7FHsN/KwyT7S8ie8y+kwKV0k3g/MlDrtPK3QFq1PLq1QMY0eMdh7stKAyLDOARAMEgFQeSnTEG75n0aEbZw1hsVgYp8ni7B7a/ScZ1pyuY770SHJQ5P+Hv0o6sVEx8=
    - secure: R2fngb8ypIUrMkjJ+aiMPoXO3EMzx2hCJbZZfEjlY0zD29EFnxX18t3Eq7M0ggyiVbys1H0ikByNRW1XckSW+IB7tO8Fi5YbFe1sDv3xrwlSytd/A1EMl9m4/oHtx75cH1UWNOSvZDIAmBNI+mTboRcaArWbtICdLWjOTZW5evs=

addons:
  sauce_connect: true
