language: node_js

node_js:
  - '0.10'

env:
  global:
    - secure: HD7y0kxo4ngWVrAhyrvxxVem9j8mW/WUN71Ny57HbDBsF3vA8JbYEo8RIuFEs9XeA5nVLsek/JoqZTlKPbMNOelwrgIixn5aqJ7u//aJGZArNTGFMyqYJ8geVEB06WQWCzpWKF4XjX7Sq4FAYyuYhsT6JSeZBB8Xp9pvewiPhAM=
    - secure: diNcl71xENVRmOvJ0rfutUTzxf4PoDNTQUfcesckOvlD/LD+7xH89Z3IkmVb7hYOXV/Uuj+YCH2V5uO4it9GliFtmDrRlyQ3om/P/BNfzJBpwG7whzVNI5lus6UH1IDOEfb/IRXMTGmEqtHJ60lhUcaLlBnpob1QKSHK8hlWK+c=

addons:
  sauce_connect: true
